version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /home/ec2-user
  - source: cdk/cdk/scripts/image_uri.sh
    destination: /home/ec2-user
hooks:
  ApplicationStart:
    - location: cdk/cdk/scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: cdk/cdk/scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
